# Generated by Django 5.1.4 on 2024-12-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(blank=True, max_length=250, null=True, verbose_name='Артикул')),
                ('name', models.CharField(max_length=500, null=True, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('image', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
