# Generated by Django 5.1.4 on 2025-01-04 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='SupProduct',
        ),
    ]
