# Generated by Django 5.1.4 on 2025-01-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_myproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='suppliers')),
                ('import_url', models.URLField(blank=True, null=True)),
                ('auto_import', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
