# Generated by Django 5.1.4 on 2025-01-07 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supproduct',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.supplier'),
        ),
    ]
