# Generated by Django 5.1.4 on 2025-01-11 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_myproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='image',
            new_name='logo',
        ),
    ]
