# Generated by Django 5.1.4 on 2025-01-11 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_rename_image_supplier_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='logo',
        ),
    ]
