# Generated by Django 5.1.4 on 2025-01-11 11:26

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_supplier_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.sup_upload_to),
        ),
    ]
