# Generated by Django 5.1.4 on 2025-01-21 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_supplier_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyProduct',
        ),
    ]
