# Generated by Django 5.1.4 on 2025-02-01 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_delete_myproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='auto_import',
        ),
    ]
