# Generated by Django 5.1.4 on 2025-02-07 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_supplier_auto_import'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_availability', to='product.product', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAvailabilityAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=500, null=True, verbose_name='Размер')),
                ('amount', models.PositiveIntegerField(null=True, verbose_name='Количество')),
                ('spa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_amount', to='product.productavailability')),
            ],
        ),
    ]
