# Generated by Django 5.1.4 on 2025-02-07 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_productavailability_productavailabilityamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productavailability',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_availability', to='product.product'),
        ),
    ]
