# Generated by Django 5.1.4 on 2025-02-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_productavailability_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на товар'),
        ),
    ]
