# Generated by Django 5.1.4 on 2025-02-28 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_alter_expense_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='expense',
            new_name='category',
        ),
    ]
