# Generated by Django 5.1.4 on 2025-02-28 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_rename_expense_expense_category'),
        ('product', '0016_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_products', to='product.product', verbose_name='Товар'),
        ),
    ]
