# Generated by Django 4.1.13 on 2025-03-07 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_expenseplatform_expense_platform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platforms', to='expense.expenseplatform', verbose_name='Платформа'),
        ),
    ]
