# Generated by Django 4.1.13 on 2025-03-13 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0007_alter_expense_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expense.expensecategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expense.expenseplatform', verbose_name='Платформа'),
        ),
    ]
