# Generated by Django 5.1.4 on 2025-02-26 10:06

import django.db.models.deletion
import order.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0016_product_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='order_imports')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inID', models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер заказа')),
                ('check_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Сумма чека')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='РЦ')),
                ('amount', models.IntegerField(null=True, verbose_name='Количество')),
                ('client_name', models.CharField(max_length=200, null=True, verbose_name="Введыть Ім'я")),
                ('client_surname', models.CharField(max_length=200, null=True, verbose_name='Введыть Прізвище')),
                ('client_patronymic', models.CharField(blank=True, max_length=200, null=True, verbose_name='Введыть по-батькові')),
                ('client_phone', models.CharField(max_length=50, null=True, verbose_name='Телефон')),
                ('client_check', models.CharField(blank=True, max_length=200, null=True, verbose_name='Чек клиента')),
                ('return_check', models.CharField(blank=True, max_length=200, null=True, verbose_name='Чек возврата')),
                ('ttn', models.CharField(blank=True, max_length=100, null=True, verbose_name='TTN')),
                ('ttn_status_code', models.IntegerField(blank=True, null=True)),
                ('ttn_status', models.CharField(blank=True, max_length=500, null=True)),
                ('ttn_address', models.CharField(blank=True, max_length=1000, null=True)),
                ('ttn_is_archive', models.BooleanField(default=False, null=True)),
                ('payment', models.CharField(blank=True, choices=[('P', 'Передплата'), ('S', 'Накладений'), ('O', 'OLX')], default='S', max_length=5, verbose_name='Оплата')),
                ('bank_check', models.ImageField(blank=True, null=True, upload_to=order.models.upload_to, verbose_name='Чек банка')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='product.product')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('delivery_man', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttn', models.CharField(blank=True, max_length=100, null=True, verbose_name='TTN')),
                ('ttn_status_code', models.IntegerField(blank=True, null=True)),
                ('ttn_date', models.DateTimeField(blank=True, null=True)),
                ('ttn_status', models.CharField(blank=True, max_length=500, null=True)),
                ('ttn_address', models.CharField(blank=True, max_length=1000, null=True)),
                ('ttn_is_archive', models.BooleanField(default=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.supplier')),
            ],
            options={
                'verbose_name': 'Возврат заказа',
                'verbose_name_plural': 'Возвраты заказов',
            },
        ),
        migrations.CreateModel(
            name='ReturnSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.supplier')),
            ],
        ),
    ]
