# Generated by Django 5.1.4 on 2025-01-16 07:11

import django.db.models.deletion
import order.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0011_supplier_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inID', models.IntegerField(blank=True, null=True, verbose_name='Номер заказа')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='РЦ')),
                ('amount', models.IntegerField(null=True, verbose_name='Количество')),
                ('client_name', models.CharField(max_length=200, null=True, verbose_name="Введыть Ім'я")),
                ('client_surname', models.CharField(max_length=200, null=True, verbose_name='Введыть Прізвище')),
                ('client_patronymic', models.CharField(blank=True, max_length=200, null=True, verbose_name='Введыть по-батькові')),
                ('client_phone', models.CharField(max_length=50, null=True, verbose_name='Телефон')),
                ('client_address', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Адрес')),
                ('client_check', models.ImageField(blank=True, null=True, upload_to=order.models.upload_to)),
                ('ttn', models.CharField(blank=True, max_length=100, null=True, verbose_name='TTN')),
                ('payment', models.CharField(blank=True, choices=[('P', 'Передплата'), ('S', 'Накладений'), ('O', 'OLX')], default='S', max_length=5, verbose_name='Оплата')),
                ('bank_check', models.ImageField(blank=True, null=True, upload_to=order.models.upload_to)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
