# Generated by Django 5.1.4 on 2025-01-16 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_content_type_order_object_id'),
        ('product', '0011_supplier_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ttn_address',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='TTN'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product', verbose_name='Продукт'),
        ),
    ]
