# Generated by Django 5.1.4 on 2025-01-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_ttn_address_alter_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client_address',
        ),
        migrations.AddField(
            model_name='order',
            name='ttn_is_archive',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ttn_status',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='TTN'),
        ),
    ]
