# Generated by Django 5.1.4 on 2025-01-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_client_address_order_ttn_is_archive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ttn_address',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='TTN Addres'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ttn_status',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='TTN Status'),
        ),
    ]
