# Generated by Django 5.1.4 on 2025-01-21 14:50

import django.db.models.deletion
import order.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_ttn_address_alter_order_ttn_status'),
        ('product', '0012_delete_myproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='object_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='bank_check',
            field=models.ImageField(blank=True, null=True, upload_to=order.models.upload_to, verbose_name='Чек банка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_check',
            field=models.ImageField(blank=True, null=True, upload_to=order.models.upload_to, verbose_name='Чек клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product'),
        ),
    ]
