# Generated by Django 5.1.4 on 2025-01-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_order_content_type_remove_order_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ttn_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ttn_address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ttn_status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
