# Generated by Django 5.1.4 on 2025-01-21 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_ttn_code_alter_order_ttn_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ttn_code',
            new_name='ttn_status_code',
        ),
    ]
