# Generated by Django 5.1.4 on 2025-01-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='inID',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер заказа'),
        ),
    ]
