# Generated by Django 5.1.4 on 2025-01-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_order_inid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_check',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Чек клиента'),
        ),
    ]
