# Generated by Django 5.1.4 on 2025-01-29 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_expensecategory_delivery_created_delivery_updated_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='ExpenseCategory',
        ),
    ]
